@ stdcall SHCreateItemFromIDList(ptr ptr ptr)
@ stdcall SHCreateItemWithParent(ptr ptr ptr ptr ptr)
@ stdcall SHCreateItemFromParsingName(wstr ptr ptr ptr)
@ stdcall SHGetStockIconInfo(long long ptr)
@ stdcall SHGetFolderPathEx(ptr long ptr ptr long)
@ stdcall SHGetKnownFolderPath(ptr long ptr ptr)
